services:
  backend:
    build: .
    container_name: fastapi_backend
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./credentials/service-account.json:/app/credentials/service-account.json
  nginx:
    image: nginx:alpine
    container_name: fastapi_nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend

volumes:
  pgdata:
