services:
  backend:
    build: .
    container_name: fastapi_backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./credentials/service-account.json:/app/credentials/service-account.json
    deploy:
      resources:
        limits:
          cpus: "1.5"
          memory: 2g
        reservations:
          cpus: "0.5"
          memory: 512m

  nginx:
    image: nginx:alpine
    container_name: fastapi_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend

volumes:
  pgdata:
