[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q --tb=short"
testpaths = [
    "tests",
]
python_files = [
    "test_*.py",
    "*_test.py",
]
python_classes = [
    "Test*",
]
python_functions = [
    "test_*",
]
markers = [
    "auth: marks tests related to authentication",
    "user: marks tests related to user management", 
    "integration: marks integration tests",
]

# Pytest environment variables
env = [
    "SECRET_KEY=test-secret-key-for-testing-only",
    "OPENAI_API_KEY=test-openai-key",
]